### ISSUE TITLE
Document search showing result with attachmentCount, but no urls for attachments

### ISSUE THREAD

**Issue by sbenthall** [regulationsgov/developers#49]
I'm getting results from the `document` endpoint that have a positive attachmentCount but with no url for accessing the attachment. For example (this is a printout of Python JSON):

    {u'agencyAcronym': u'DOD',
     u'allowLateComment': False,
     u'attachmentCount': 1,
     u'commentDueDate': u'2007-06-11T23:59:59-04:00',
     u'commentStartDate': u'2007-04-11T00:00:00-04:00',
     u'commentText': u'Please see attached.\n',
     u'docketId': u'DOD-2006-OS-0216',
     u'docketTitle': u'Limitations on Terms of Consumer Credit Extended to Service Members and Dependents',
     u'docketType': u'Rulemaking',
     u'documentId': u'DOD-2006-OS-0216-0230',
     u'documentStatus': u'Posted',
     u'documentType': u'Public Submission',
     u'numberOfCommentsReceived': 1,
     u'openForComment': False,
     u'postedDate': u'2007-06-11T00:00:00-04:00',
     u'rin': u'0790-AI20',
     u'title': u"World's Foremost Bank"}

Is this a bug? I see there's a [field](http://regulationsgov.github.io/developers/fields/) for `attachments` but I don't know under what conditions to expect to get that in the query response. Thanks!

**Comment by shawnjohnson** [comment]
If the attachmentCount is greater than 1 you should expect to see the attachments field.  Below is the JSON for attachments that I get for the given document id.
```json
"attachments": [
{
"attachmentOrderNumber": 1,
"fileFormats": [
"https://api.data.gov/regulations/v3/download?documentId=DOD-2006-OS-0216-0230&attachmentNumber=1&contentType=pdf"
],
"postingRestriction": "No_restrictions",
"title": "World's Foremost Bank Attachment"
}
],
```

**Comment by sbenthall** [comment]
Ok, this works for me now. I think my original ticket was invalid--I was looking at data from the `documents` endpoint. Thanks for your help!
