### ISSUE TITLE
Interactive API breaks on HTTPS

### ISSUE THREAD

**Issue by rhewitt22** [regulationsgov/developers#69]
With HTTPS everywhere enabled the Interactive API page.  Mixed content errors for `documents.json` and `dockets.json`.

![screen shot 2017-03-13 at 5 03 24 pm](https://cloud.githubusercontent.com/assets/3673374/23875228/1166f5b0-080f-11e7-9eac-1a5d0ecd3ca2.jpg)

**Comment by shawnjohnson** [comment]
This issue should be resolved now.  Please reply if the issue persists.
