### ISSUE TITLE
api key error

### ISSUE THREAD

**Issue by pklopf** [regulationsgov/developers#76]
Hi all,
I have been using this API before...now, however, it seems that my api key is not working any more..

Whenever I make a request via the "Search for Documents"-interactive API, I get an error:

Request URL

https://api.data.gov:443/regulations/v3/documents.json?api_key=DEMO_KEY&dct=FR&dktid=SEC-2012-0044

Response Body

{
  "error": {
    "code": "API_KEY_UNAUTHORIZED",
    "message": "The api_key supplied is not authorized to access the given service. Contact us at https://www.regulations.gov/contactUs for assistance"
  }
}

Response Code

403

Can you tell me what's going wrong, please?

**Comment by gisrael** [comment]
I've experienced the same issue. I tried requesting a new key, and it failed as well.

**Comment by pklopf** [comment]
I really hope the Api works again soon!! Getting data on the regulations is a make or break of my dissertation.

**Comment by shawnjohnson** [comment]
The Regulations.gov API is taking action to conserve system resources. Beginning immediately, we will limit access to one account per organization and require approval for enabling accounts. We will still maintain rate limits. All requests for enabling accounts should be sent to regulations@erulemakinghelpdesk.com.
